server:
  port: ${PORT:5555}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka}
