server:
  port: ${PORT:5555}

spring:
  sleuth.sampler.percentage: 1
  zipkin:
    baseUrl: ${ZIPKIN_SERVER_URI:localhost:9411}

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka}
